version: "3.8"

services:
  sftpgo:
    image: drakkan/sftpgo:latest
    container_name: sftpgo
    ports:
      - "2022:2022"     # Porta do SFTP
      - "8080:8080"     # Painel Web
    environment:
#      - SFTPGO_DEFAULT_ADMIN_USERNAME=
#      - SFTPGO_DEFAULT_ADMIN_PASSWORD=
      - SFTPGO_HTTPD__BINDINGS__0__PORT=8080
      - SFTPGO_SFTPD__BINDINGS__0__PORT=2022
    volumes:
      - ./data:/var/lib/sftpgo # diretorio dos arquivos de usuarios
      - ./dataFiles:/srv/sftpgo # diretorio dos arquivos locais
    restart: unless-stopped
