version: '3.8'

services:
  sftpgo:
    image: drakkan/sftpgo:latest
    container_name: sftpgo
    depends_on:
      - mysql
    ports:
      - "8080:8080"   # Painel web
      - "2022:2022"   # SFTP
    environment:
      - SFTPGO_DATA_PROVIDER__DRIVER=mysql
      - SFTPGO_DATA_PROVIDER__HOST=mysql
      - SFTPGO_DATA_PROVIDER__PORT=3306
      - SFTPGO_DATA_PROVIDER__NAME=sftpgo
      - SFTPGO_DATA_PROVIDER__USERNAME=sftpuser
      - SFTPGO_DATA_PROVIDER__PASSWORD=sftppass
      - SFTPGO_DB__SSL_MODE=disable
      - SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN=true #Variavel que ativa a criação de admin ao iniciar o container.
      - SFTPGO_DEFAULT_ADMIN_USERNAME="administrator"
      - SFTPGO_DEFAULT_ADMIN_PASSWORD="qDK8P3SEhW4tknoab9tx"
    volumes:
      - ./data:/var/lib/sftpgo
      - ./dataFiles:/srv/sftpgo
    restart: unless-stopped
